### DISCUSSION TITLE
Update the plugin to support UI Kit 2 frontend projects

### DISCUSSION THREAD

**Discussion by tbinna** [toolsplus/nx-forge#71] [Ideas]
The idea is to support [UI Kit 2 front-end projects](https://developer.atlassian.com/platform/forge/ui-kit-2/). These work very similar to Custom UI React projects, and if they are written in Typescript, we should compile them to JS before passing them as a build artifact to Forge.

The main work to be done here is quite minimal and includes replacing Custom UI/Custom UIs terms throughout the project with the more generic Resource/Resources terms. For example, today, by default, [the plugin generates Custom UI dependencies into a folder called customUI](https://github.com/toolsplus/nx-forge/blob/d656cbb61a008d4112a847262e9e88be2f65cf32/packages/nx-forge/src/executors/build/lib/normalize-options.ts#L14). This and the associated build executor option must be changed to `resources`.

To be explored is if we could provide a generator configuring UI Kit 2 projects based on [the React app generator](https://nx.dev/nx-api/react/generators/application).

**Comment by tbinna** [comment]
I did some testing on this, and there is more work required.

With reference to the manifest example below:

* Forge requires the UI Kit 2 resource path to point to the entry point file (for Custom UI, we point the resource to the folder containing the resource). ~~This may require us to introduce a mechanism to distinguish UI Kit 2 frontend project from Custom UI projects.~~ We should be able to infer if a resource is UI Kit 2 by looking at the module that's using it. The module will have to specify `render: native` for UI Kit 2 user interfaces.
* I am not clear yet what generator or generator configuration works best. If we write UI Kit 2 in Typescript we want to build it to JS before deployment. The build should support assets such as images according to the UI Kit 2 spec.

Manifest example:
```yaml
modules:
  jira:globalPage:
    - key: ui-kit-2-test-hello-world-global-page
      resource: main
      resolver:
        function: resolver
      render: native
      title: UI Kit 2 Test
  function:
    - key: resolver
      handler: index.handler
resources:
  - key: main
    path: customUI/ui-kit-2/main.js
app:
  id: ari:cloud:ecosystem::app/
```
