### ISSUE TITLE
nx serve does not start tunnel

### ISSUE THREAD

**Issue by antonversal** [toolsplus/nx-forge#132]
Hello,
Thanks for the project.

It seems that `nx serve` only serves the forge app, not the custom app, and it does not start tunneling. Deploying and installing work just fine. Any change to the custom UI app does not start rebuilding, but changes to the forge app do.

```
nx serve simple-project

> nx run simple-project:serve

> webpack-cli serve --node-env=development

<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:8080/, http://[::1]:8080/
<i> [webpack-dev-server] On Your Network (IPv4): http://192.168.178.20:8080/
<i> [webpack-dev-server] Content not from webpack is served from '/Users/ant/projects/simple-project/apps/simple-project/public' directory
chunk (runtime: index) index.js (index) 5.58 KiB (javascript) 22.6 KiB (runtime) [entry] [rendered]
chunk (runtime: main) main.js (main) 5.58 KiB (javascript) 22.6 KiB (runtime) [entry] [rendered]
webpack compiled successfully (bf81ddf32d5f7636)
```

`manifest.yml`:
```yaml
modules:
  jira:projectPage:
    - key: project-page
      title: Project page Custom UI
      layout: basic
      resource: project-page
      resolver:
        function: resolver
  function:
    - key: resolver
      handler: index.handler
resources:
  - key: project-page
    path: simple-project-ui
    tunnel:
      port: 4200
permissions:
  content:
    styles:
      - unsafe-inline
app:
  id: ari:cloud:ecosystem::app/1111111-1111-111
  runtime:
   name: nodejs18.x
```
